//! `SeaORM` Entity. Generated by sea-orm-cli -h 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "t_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub user_no: u64,
    pub user_code: String,
    #[sea_orm(unique)]
    pub username: String,
    pub nickname: String,
    pub password: String,
    pub salt: String,
    pub email: String,
    pub phone: String,
    pub login_at: DateTime,
    pub login_token: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: DateTime,
    pub version: u8,
    #[sea_orm(column_name = "is_deleted")]
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
