version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - TZ=UTC
      - LANG=en_US.UTF-8
    networks:
      - aphrodite-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "test", "-h", "db"]
      interval: 30s
      timeout: 10s
      retries: 5

  cache:
    image: redis:7-alpine
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - aphrodite-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    image: aphrodite-rs:latest
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - aphrodite-network
    restart: unless-stopped
    depends_on:
      - db
      - cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  aphrodite-network:
    driver: bridge
